
// On a changé le nom de l'attribut '2.5d' en '2$5d', car JS n'accepte pas le point dans une clé
// Et on a rajouté le préfixe 'tag_' car JS n'accepte pas les clés commençant par des chiffres
// Et on a changé '&' en 'and' parce que JS n'accepte pas non plus les clés contenant des '&'
// Il lui faudrait une petite leçon de tolérance à ce JS !! 🙃

const dbIndexScheme = {
    index: 'project_s6_steamspy_tag_data',
    body: {
        mappings: {
            properties: {
                id: { type: 'integer' },
                tag_1980s: { type: 'integer' },
                tag_1990s:  { type: 'integer' },
                tag_2$5d:  { type: 'integer' },
                tag_2d:  { type: 'integer' },
                tag_2d_fighter:  { type: 'integer' },
                tag_360_video:  { type: 'integer' },
                tag_3d:  { type: 'integer' },
                tag_3d_platformer:  { type: 'integer' },
                tag_3d_vision:  { type: 'integer' },
                tag_4_player_local:  { type: 'integer' },
                tag_4x:  { type: 'integer' },
                tag_6dof:  { type: 'integer' },
                tag_atv:  { type: 'integer' },
                tag_abstract:  { type: 'integer' },
                tag_action:  { type: 'integer' },
                tag_action_rpg:  { type: 'integer' },
                tag_action_adventure:  { type: 'integer' },
                tag_addictive:  { type: 'integer' },
                tag_adventure:  { type: 'integer' },
                tag_agriculture:  { type: 'integer' },
                tag_aliens:  { type: 'integer' },
                tag_alternate_history:  { type: 'integer' },
                tag_america:  { type: 'integer' },
                tag_animation_and_modeling:  { type: 'integer' },
                tag_anime:  { type: 'integer' },
                tag_arcade:  { type: 'integer' },
                tag_arena_shooter:  { type: 'integer' },
                tag_artificial_intelligence:  { type: 'integer' },
                tag_assassin:  { type: 'integer' },
                tag_asynchronous_multiplayer:  { type: 'integer' },
                tag_atmospheric:  { type: 'integer' },
                tag_audio_production:  { type: 'integer' },
                tag_bmx:  { type: 'integer' },
                tag_base_building:  { type: 'integer' },
                tag_baseball:  { type: 'integer' },
                tag_based_on_a_novel:  { type: 'integer' },
                tag_basketball:  { type: 'integer' },
                tag_batman:  { type: 'integer' },
                tag_battle_royale:  { type: 'integer' },
                tag_beat_em_up:  { type: 'integer' },
                tag_beautiful:  { type: 'integer' },
                tag_benchmark:  { type: 'integer' },
                tag_bikes:  { type: 'integer' },
                tag_blood:  { type: 'integer' },
                tag_board_game:  { type: 'integer' },
                tag_bowling:  { type: 'integer' },
                tag_building:  { type: 'integer' },
                tag_bullet_hell:  { type: 'integer' },
                tag_bullet_time:  { type: 'integer' },
                tag_crpg:  { type: 'integer' },
                tag_capitalism:  { type: 'integer' },
                tag_card_game:  { type: 'integer' },
                tag_cartoon:  { type: 'integer' },
                tag_cartoony:  { type: 'integer' },
                tag_casual:  { type: 'integer' },
                tag_cats:  { type: 'integer' },
                tag_character_action_game:  { type: 'integer' },
                tag_character_customization:  { type: 'integer' },
                tag_chess:  { type: 'integer' },
                tag_choices_matter:  { type: 'integer' },
                tag_choose_your_own_adventure:  { type: 'integer' },
                tag_cinematic:  { type: 'integer' },
                tag_city_builder:  { type: 'integer' },
                tag_class_based:  { type: 'integer' },
                tag_classic:  { type: 'integer' },
                tag_clicker:  { type: 'integer' },
                tag_co_op:  { type: 'integer' },
                tag_co_op_campaign:  { type: 'integer' },
                tag_cold_war:  { type: 'integer' },
                tag_colorful:  { type: 'integer' },
                tag_comedy:  { type: 'integer' },
                tag_comic_book:  { type: 'integer' },
                tag_competitive:  { type: 'integer' },
                tag_conspiracy:  { type: 'integer' },
                tag_controller:  { type: 'integer' },
                tag_conversation:  { type: 'integer' },
                tag_crafting:  { type: 'integer' },
                tag_crime:  { type: 'integer' },
                tag_crowdfunded:  { type: 'integer' },
                tag_cult_classic:  { type: 'integer' },
                tag_cute:  { type: 'integer' },
                tag_cyberpunk:  { type: 'integer' },
                tag_cycling:  { type: 'integer' },
                tag_dark:  { type: 'integer' },
                tag_dark_comedy:  { type: 'integer' },
                tag_dark_fantasy:  { type: 'integer' },
                tag_dark_humor:  { type: 'integer' },
                tag_dating_sim:  { type: 'integer' },
                tag_demons:  { type: 'integer' },
                tag_design_and_illustration:  { type: 'integer' },
                tag_destruction:  { type: 'integer' },
                tag_detective:  { type: 'integer' },
                tag_difficult:  { type: 'integer' },
                tag_dinosaurs:  { type: 'integer' },
                tag_diplomacy:  { type: 'integer' },
                tag_documentary:  { type: 'integer' },
                tag_dog:  { type: 'integer' },
                tag_dragons:  { type: 'integer' },
                tag_drama:  { type: 'integer' },
                tag_driving:  { type: 'integer' },
                tag_dungeon_crawler:  { type: 'integer' },
                tag_dungeons_and_dragons:  { type: 'integer' },
                tag_dynamic_narration:  { type: 'integer' },
                tag_dystopian:  { type: 'integer' },
                tag_early_access:  { type: 'integer' },
                tag_economy:  { type: 'integer' },
                tag_education:  { type: 'integer' },
                tag_emotional:  { type: 'integer' },
                tag_epic:  { type: 'integer' },
                tag_episodic:  { type: 'integer' },
                tag_experience:  { type: 'integer' },
                tag_experimental:  { type: 'integer' },
                tag_exploration:  { type: 'integer' },
                tag_fmv:  { type: 'integer' },
                tag_fps:  { type: 'integer' },
                tag_faith:  { type: 'integer' },
                tag_family_friendly:  { type: 'integer' },
                tag_fantasy:  { type: 'integer' },
                tag_fast_paced:  { type: 'integer' },
                tag_feature_film:  { type: 'integer' },
                tag_female_protagonist:  { type: 'integer' },
                tag_fighting:  { type: 'integer' },
                tag_first_person:  { type: 'integer' },
                tag_fishing:  { type: 'integer' },
                tag_flight:  { type: 'integer' },
                tag_football:  { type: 'integer' },
                tag_foreign:  { type: 'integer' },
                tag_free_to_play:  { type: 'integer' },
                tag_funny:  { type: 'integer' },
                tag_futuristic:  { type: 'integer' },
                tag_gambling:  { type: 'integer' },
                tag_game_development:  { type: 'integer' },
                tag_gamemaker:  { type: 'integer' },
                tag_games_workshop:  { type: 'integer' },
                tag_gaming:  { type: 'integer' },
                tag_god_game:  { type: 'integer' },
                tag_golf:  { type: 'integer' },
                tag_gore:  { type: 'integer' },
                tag_gothic:  { type: 'integer' },
                tag_grand_strategy:  { type: 'integer' },
                tag_great_soundtrack:  { type: 'integer' },
                tag_grid_based_movement:  { type: 'integer' },
                tag_gun_customization:  { type: 'integer' },
                tag_hack_and_slash:  { type: 'integer' },
                tag_hacking:  { type: 'integer' },
                tag_hand_drawn:  { type: 'integer' },
                tag_hardware:  { type: 'integer' },
                tag_heist:  { type: 'integer' },
                tag_hex_grid:  { type: 'integer' },
                tag_hidden_object:  { type: 'integer' },
                tag_historical:  { type: 'integer' },
                tag_hockey:  { type: 'integer' },
                tag_horror:  { type: 'integer' },
                tag_horses:  { type: 'integer' },
                tag_hunting:  { type: 'integer' },
                tag_illuminati:  { type: 'integer' },
                tag_indie:  { type: 'integer' },
                tag_intentionally_awkward_controls:  { type: 'integer' },
                tag_interactive_fiction:  { type: 'integer' },
                tag_inventory_management:  { type: 'integer' },
                tag_investigation:  { type: 'integer' },
                tag_isometric:  { type: 'integer' },
                tag_jrpg:  { type: 'integer' },
                tag_jet:  { type: 'integer' },
                tag_kickstarter:  { type: 'integer' },
                tag_lego:  { type: 'integer' },
                tag_lara_croft:  { type: 'integer' },
                tag_lemmings:  { type: 'integer' },
                tag_level_editor:  { type: 'integer' },
                tag_linear:  { type: 'integer' },
                tag_local_co_op:  { type: 'integer' },
                tag_local_multiplayer:  { type: 'integer' },
                tag_logic:  { type: 'integer' },
                tag_loot:  { type: 'integer' },
                tag_lore_rich:  { type: 'integer' },
                tag_lovecraftian:  { type: 'integer' },
                tag_mmorpg:  { type: 'integer' },
                tag_moba:  { type: 'integer' },
                tag_magic:  { type: 'integer' },
                tag_management:  { type: 'integer' },
                tag_mars:  { type: 'integer' },
                tag_martial_arts:  { type: 'integer' },
                tag_massively_multiplayer:  { type: 'integer' },
                tag_masterpiece:  { type: 'integer' },
                tag_match_3:  { type: 'integer' },
                tag_mature:  { type: 'integer' },
                tag_mechs:  { type: 'integer' },
                tag_medieval:  { type: 'integer' },
                tag_memes:  { type: 'integer' },
                tag_metroidvania:  { type: 'integer' },
                tag_military:  { type: 'integer' },
                tag_mini_golf:  { type: 'integer' },
                tag_minigames:  { type: 'integer' },
                tag_minimalist:  { type: 'integer' },
                tag_mining:  { type: 'integer' },
                tag_mod:  { type: 'integer' },
                tag_moddable:  { type: 'integer' },
                tag_modern:  { type: 'integer' },
                tag_motocross:  { type: 'integer' },
                tag_motorbike:  { type: 'integer' },
                tag_mouse_only:  { type: 'integer' },
                tag_movie:  { type: 'integer' },
                tag_multiplayer:  { type: 'integer' },
                tag_multiple_endings:  { type: 'integer' },
                tag_music:  { type: 'integer' },
                tag_music_based_procedural_generation:  { type: 'integer' },
                tag_mystery:  { type: 'integer' },
                tag_mystery_dungeon:  { type: 'integer' },
                tag_mythology:  { type: 'integer' },
                tag_nsfw:  { type: 'integer' },
                tag_narration:  { type: 'integer' },
                tag_naval:  { type: 'integer' },
                tag_ninja:  { type: 'integer' },
                tag_noir:  { type: 'integer' },
                tag_nonlinear:  { type: 'integer' },
                tag_nudity:  { type: 'integer' },
                tag_offroad:  { type: 'integer' },
                tag_old_school:  { type: 'integer' },
                tag_on_rails_shooter:  { type: 'integer' },
                tag_online_co_op:  { type: 'integer' },
                tag_open_world:  { type: 'integer' },
                tag_otome:  { type: 'integer' },
                tag_parkour:  { type: 'integer' },
                tag_parody:  { type: 'integer' },
                tag_party_based_rpg:  { type: 'integer' },
                tag_perma_death:  { type: 'integer' },
                tag_philisophical:  { type: 'integer' },
                tag_photo_editing:  { type: 'integer' },
                tag_physics:  { type: 'integer' },
                tag_pinball:  { type: 'integer' },
                tag_pirates:  { type: 'integer' },
                tag_pixel_graphics:  { type: 'integer' },
                tag_platformer:  { type: 'integer' },
                tag_point_and_click:  { type: 'integer' },
                tag_political:  { type: 'integer' },
                tag_politics:  { type: 'integer' },
                tag_pool:  { type: 'integer' },
                tag_post_apocalyptic:  { type: 'integer' },
                tag_procedural_generation:  { type: 'integer' },
                tag_programming:  { type: 'integer' },
                tag_psychedelic:  { type: 'integer' },
                tag_psychological:  { type: 'integer' },
                tag_psychological_horror:  { type: 'integer' },
                tag_puzzle:  { type: 'integer' },
                tag_puzzle_platformer:  { type: 'integer' },
                tag_pve:  { type: 'integer' },
                tag_pvp:  { type: 'integer' },
                tag_quick_time_events:  { type: 'integer' },
                tag_rpg:  { type: 'integer' },
                tag_rpgmaker:  { type: 'integer' },
                tag_rts:  { type: 'integer' },
                tag_racing:  { type: 'integer' },
                tag_real_time_tactics:  { type: 'integer' },
                tag_real_time:  { type: 'integer' },
                tag_real_time_with_pause:  { type: 'integer' },
                tag_realistic:  { type: 'integer' },
                tag_relaxing:  { type: 'integer' },
                tag_remake:  { type: 'integer' },
                tag_replay_value:  { type: 'integer' },
                tag_resource_management:  { type: 'integer' },
                tag_retro:  { type: 'integer' },
                tag_rhythm:  { type: 'integer' },
                tag_robots:  { type: 'integer' },
                tag_rogue_like:  { type: 'integer' },
                tag_rogue_lite:  { type: 'integer' },
                tag_romance:  { type: 'integer' },
                tag_rome:  { type: 'integer' },
                tag_runner:  { type: 'integer' },
                tag_sailing:  { type: 'integer' },
                tag_sandbox:  { type: 'integer' },
                tag_satire:  { type: 'integer' },
                tag_sci_fi:  { type: 'integer' },
                tag_science:  { type: 'integer' },
                tag_score_attack:  { type: 'integer' },
                tag_sequel:  { type: 'integer' },
                tag_sexual_content:  { type: 'integer' },
                tag_shoot_em_up:  { type: 'integer' },
                tag_shooter:  { type: 'integer' },
                tag_short:  { type: 'integer' },
                tag_side_scroller:  { type: 'integer' },
                tag_silent_protagonist:  { type: 'integer' },
                tag_simulation:  { type: 'integer' },
                tag_singleplayer:  { type: 'integer' },
                tag_skateboarding:  { type: 'integer' },
                tag_skating:  { type: 'integer' },
                tag_skiing:  { type: 'integer' },
                tag_sniper:  { type: 'integer' },
                tag_snow:  { type: 'integer' },
                tag_snowboarding:  { type: 'integer' },
                tag_soccer:  { type: 'integer' },
                tag_software:  { type: 'integer' },
                tag_software_training:  { type: 'integer' },
                tag_sokoban:  { type: 'integer' },
                tag_souls_like:  { type: 'integer' },
                tag_soundtrack:  { type: 'integer' },
                tag_space:  { type: 'integer' },
                tag_space_sim:  { type: 'integer' },
                tag_spectacle_fighter:  { type: 'integer' },
                tag_spelling:  { type: 'integer' },
                tag_split_screen:  { type: 'integer' },
                tag_sports:  { type: 'integer' },
                tag_star_wars:  { type: 'integer' },
                tag_stealth:  { type: 'integer' },
                tag_steam_machine:  { type: 'integer' },
                tag_steampunk:  { type: 'integer' },
                tag_story_rich:  { type: 'integer' },
                tag_strategy:  { type: 'integer' },
                tag_strategy_rpg:  { type: 'integer' },
                tag_stylized:  { type: 'integer' },
                tag_submarine:  { type: 'integer' },
                tag_superhero:  { type: 'integer' },
                tag_supernatural:  { type: 'integer' },
                tag_surreal:  { type: 'integer' },
                tag_survival:  { type: 'integer' },
                tag_survival_horror:  { type: 'integer' },
                tag_swordplay:  { type: 'integer' },
                tag_tactical:  { type: 'integer' },
                tag_tactical_rpg:  { type: 'integer' },
                tag_tanks:  { type: 'integer' },
                tag_team_based:  { type: 'integer' },
                tag_tennis:  { type: 'integer' },
                tag_text_based:  { type: 'integer' },
                tag_third_person:  { type: 'integer' },
                tag_third_person_shooter:  { type: 'integer' },
                tag_thriller:  { type: 'integer' },
                tag_time_attack:  { type: 'integer' },
                tag_time_management:  { type: 'integer' },
                tag_time_manipulation:  { type: 'integer' },
                tag_time_travel:  { type: 'integer' },
                tag_top_down:  { type: 'integer' },
                tag_top_down_shooter:  { type: 'integer' },
                tag_touch_friendly:  { type: 'integer' },
                tag_tower_defense:  { type: 'integer' },
                tag_trackir:  { type: 'integer' },
                tag_trading:  { type: 'integer' },
                tag_trading_card_game:  { type: 'integer' },
                tag_trains:  { type: 'integer' },
                tag_transhumanism:  { type: 'integer' },
                tag_turn_based:  { type: 'integer' },
                tag_turn_based_combat:  { type: 'integer' },
                tag_turn_based_strategy:  { type: 'integer' },
                tag_turn_based_tactics:  { type: 'integer' },
                tag_tutorial:  { type: 'integer' },
                tag_twin_stick_shooter:  { type: 'integer' },
                tag_typing:  { type: 'integer' },
                tag_underground:  { type: 'integer' },
                tag_underwater:  { type: 'integer' },
                tag_unforgiving:  { type: 'integer' },
                tag_utilities:  { type: 'integer' },
                tag_vr:  { type: 'integer' },
                tag_vr_only:  { type: 'integer' },
                tag_vampire:  { type: 'integer' },
                tag_video_production:  { type: 'integer' },
                tag_villain_protagonist:  { type: 'integer' },
                tag_violent:  { type: 'integer' },
                tag_visual_novel:  { type: 'integer' },
                tag_voice_control:  { type: 'integer' },
                tag_voxel:  { type: 'integer' },
                tag_walking_simulator:  { type: 'integer' },
                tag_war:  { type: 'integer' },
                tag_wargame:  { type: 'integer' },
                tag_warhammer_40k:  { type: 'integer' },
                tag_web_publishing:  { type: 'integer' },
                tag_werewolves:  { type: 'integer' },
                tag_western:  { type: 'integer' },
                tag_word_game:  { type: 'integer' },
                tag_world_war_i:  { type: 'integer' },
                tag_world_war_ii:  { type: 'integer' },
                tag_wrestling:  { type: 'integer' },
                tag_zombies:  { type: 'integer' },
                tag_e_sports:  { type: 'integer' }
            }
        }
    }
};

const objectImport = data => ({
    id: data['appid'],
    tag_1980s: data['1980s'],
    tag_1990s: data['1990s'],
    tag_2$5d: data['2.5d'],
    tag_2d: data['2d'],
    tag_2d_fighter: data['2d_fighter'],
    tag_360_video: data['360_video'],
    tag_3d: data['3d'],
    tag_3d_platformer: data['3d_platformer'],
    tag_3d_vision: data['3d_vision'],
    tag_4_player_local: data['4_player_local'],
    tag_4x: data['4x'],
    tag_6dof: data['6dof'],
    tag_atv: data['atv'],
    tag_abstract: data['abstract'],
    tag_action: data['action'],
    tag_action_rpg: data['action_rpg'],
    tag_action_adventure: data['action_adventure'],
    tag_addictive: data['addictive'],
    tag_adventure: data['adventure'],
    tag_agriculture: data['agriculture'],
    tag_aliens: data['aliens'],
    tag_alternate_history: data['alternate_history'],
    tag_america: data['america'],
    tag_animation_and_modeling: data['animation_and_modeling'],
    tag_anime: data['anime'],
    tag_arcade: data['arcade'],
    tag_arena_shooter: data['arena_shooter'],
    tag_artificial_intelligence: data['artificial_intelligence'],
    tag_assassin: data['assassin'],
    tag_asynchronous_multiplayer: data['asynchronous_multiplayer'],
    tag_atmospheric: data['atmospheric'],
    tag_audio_production: data['audio_production'],
    tag_bmx: data['bmx'],
    tag_base_building: data['base_building'],
    tag_baseball: data['baseball'],
    tag_based_on_a_novel: data['based_on_a_novel'],
    tag_basketball: data['basketball'],
    tag_batman: data['batman'],
    tag_battle_royale: data['battle_royale'],
    tag_beat_em_up: data['beat_em_up'],
    tag_beautiful: data['beautiful'],
    tag_benchmark: data['benchmark'],
    tag_bikes: data['bikes'],
    tag_blood: data['blood'],
    tag_board_game: data['board_game'],
    tag_bowling: data['bowling'],
    tag_building: data['building'],
    tag_bullet_hell: data['bullet_hell'],
    tag_bullet_time: data['bullet_time'],
    tag_crpg: data['crpg'],
    tag_capitalism: data['capitalism'],
    tag_card_game: data['card_game'],
    tag_cartoon: data['cartoon'],
    tag_cartoony: data['cartoony'],
    tag_casual: data['casual'],
    tag_cats: data['cats'],
    tag_character_action_game: data['character_action_game'],
    tag_character_customization: data['character_customization'],
    tag_chess: data['chess'],
    tag_choices_matter: data['choices_matter'],
    tag_choose_your_own_adventure: data['choose_your_own_adventure'],
    tag_cinematic: data['cinematic'],
    tag_city_builder: data['city_builder'],
    tag_class_based: data['class_based'],
    tag_classic: data['classic'],
    tag_clicker: data['clicker'],
    tag_co_op: data['co_op'],
    tag_co_op_campaign: data['co_op_campaign'],
    tag_cold_war: data['cold_war'],
    tag_colorful: data['colorful'],
    tag_comedy: data['comedy'],
    tag_comic_book: data['comic_book'],
    tag_competitive: data['competitive'],
    tag_conspiracy: data['conspiracy'],
    tag_controller: data['controller'],
    tag_conversation: data['conversation'],
    tag_crafting: data['crafting'],
    tag_crime: data['crime'],
    tag_crowdfunded: data['crowdfunded'],
    tag_cult_classic: data['cult_classic'],
    tag_cute: data['cute'],
    tag_cyberpunk: data['cyberpunk'],
    tag_cycling: data['cycling'],
    tag_dark: data['dark'],
    tag_dark_comedy: data['dark_comedy'],
    tag_dark_fantasy: data['dark_fantasy'],
    tag_dark_humor: data['dark_humor'],
    tag_dating_sim: data['dating_sim'],
    tag_demons: data['demons'],
    tag_design_and_illustration: data['design_and_illustration'],
    tag_destruction: data['destruction'],
    tag_detective: data['detective'],
    tag_difficult: data['difficult'],
    tag_dinosaurs: data['dinosaurs'],
    tag_diplomacy: data['diplomacy'],
    tag_documentary: data['documentary'],
    tag_dog: data['dog'],
    tag_dragons: data['dragons'],
    tag_drama: data['drama'],
    tag_driving: data['driving'],
    tag_dungeon_crawler: data['dungeon_crawler'],
    tag_dungeons_and_dragons: data['dungeons_and_dragons'],
    tag_dynamic_narration: data['dynamic_narration'],
    tag_dystopian: data['dystopian'],
    tag_early_access: data['early_access'],
    tag_economy: data['economy'],
    tag_education: data['education'],
    tag_emotional: data['emotional'],
    tag_epic: data['epic'],
    tag_episodic: data['episodic'],
    tag_experience: data['experience'],
    tag_experimental: data['experimental'],
    tag_exploration: data['exploration'],
    tag_fmv: data['fmv'],
    tag_fps: data['fps'],
    tag_faith: data['faith'],
    tag_family_friendly: data['family_friendly'],
    tag_fantasy: data['fantasy'],
    tag_fast_paced: data['fast_paced'],
    tag_feature_film: data['feature_film'],
    tag_female_protagonist: data['female_protagonist'],
    tag_fighting: data['fighting'],
    tag_first_person: data['first_person'],
    tag_fishing: data['fishing'],
    tag_flight: data['flight'],
    tag_football: data['football'],
    tag_foreign: data['foreign'],
    tag_free_to_play: data['free_to_play'],
    tag_funny: data['funny'],
    tag_futuristic: data['futuristic'],
    tag_gambling: data['gambling'],
    tag_game_development: data['game_development'],
    tag_gamemaker: data['gamemaker'],
    tag_games_workshop: data['games_workshop'],
    tag_gaming: data['gaming'],
    tag_god_game: data['god_game'],
    tag_golf: data['golf'],
    tag_gore: data['gore'],
    tag_gothic: data['gothic'],
    tag_grand_strategy: data['grand_strategy'],
    tag_great_soundtrack: data['great_soundtrack'],
    tag_grid_based_movement: data['grid_based_movement'],
    tag_gun_customization: data['gun_customization'],
    tag_hack_and_slash: data['hack_and_slash'],
    tag_hacking: data['hacking'],
    tag_hand_drawn: data['hand_drawn'],
    tag_hardware: data['hardware'],
    tag_heist: data['heist'],
    tag_hex_grid: data['hex_grid'],
    tag_hidden_object: data['hidden_object'],
    tag_historical: data['historical'],
    tag_hockey: data['hockey'],
    tag_horror: data['horror'],
    tag_horses: data['horses'],
    tag_hunting: data['hunting'],
    tag_illuminati: data['illuminati'],
    tag_indie: data['indie'],
    tag_intentionally_awkward_controls: data['intentionally_awkward_controls'],
    tag_interactive_fiction: data['interactive_fiction'],
    tag_inventory_management: data['inventory_management'],
    tag_investigation: data['investigation'],
    tag_isometric: data['isometric'],
    tag_jrpg: data['jrpg'],
    tag_jet: data['jet'],
    tag_kickstarter: data['kickstarter'],
    tag_lego: data['lego'],
    tag_lara_croft: data['lara_croft'],
    tag_lemmings: data['lemmings'],
    tag_level_editor: data['level_editor'],
    tag_linear: data['linear'],
    tag_local_co_op: data['local_co_op'],
    tag_local_multiplayer: data['local_multiplayer'],
    tag_logic: data['logic'],
    tag_loot: data['loot'],
    tag_lore_rich: data['lore_rich'],
    tag_lovecraftian: data['lovecraftian'],
    tag_mmorpg: data['mmorpg'],
    tag_moba: data['moba'],
    tag_magic: data['magic'],
    tag_management: data['management'],
    tag_mars: data['mars'],
    tag_martial_arts: data['martial_arts'],
    tag_massively_multiplayer: data['massively_multiplayer'],
    tag_masterpiece: data['masterpiece'],
    tag_match_3: data['match_3'],
    tag_mature: data['mature'],
    tag_mechs: data['mechs'],
    tag_medieval: data['medieval'],
    tag_memes: data['memes'],
    tag_metroidvania: data['metroidvania'],
    tag_military: data['military'],
    tag_mini_golf: data['mini_golf'],
    tag_minigames: data['minigames'],
    tag_minimalist: data['minimalist'],
    tag_mining: data['mining'],
    tag_mod: data['mod'],
    tag_moddable: data['moddable'],
    tag_modern: data['modern'],
    tag_motocross: data['motocross'],
    tag_motorbike: data['motorbike'],
    tag_mouse_only: data['mouse_only'],
    tag_movie: data['movie'],
    tag_multiplayer: data['multiplayer'],
    tag_multiple_endings: data['multiple_endings'],
    tag_music: data['music'],
    tag_music_based_procedural_generation: data['music_based_procedural_generation'],
    tag_mystery: data['mystery'],
    tag_mystery_dungeon: data['mystery_dungeon'],
    tag_mythology: data['mythology'],
    tag_nsfw: data['nsfw'],
    tag_narration: data['narration'],
    tag_naval: data['naval'],
    tag_ninja: data['ninja'],
    tag_noir: data['noir'],
    tag_nonlinear: data['nonlinear'],
    tag_nudity: data['nudity'],
    tag_offroad: data['offroad'],
    tag_old_school: data['old_school'],
    tag_on_rails_shooter: data['on_rails_shooter'],
    tag_online_co_op: data['online_co_op'],
    tag_open_world: data['open_world'],
    tag_otome: data['otome'],
    tag_parkour: data['parkour'],
    tag_parody: data['parody'],
    tag_party_based_rpg: data['party_based_rpg'],
    tag_perma_death: data['perma_death'],
    tag_philisophical: data['philisophical'],
    tag_photo_editing: data['photo_editing'],
    tag_physics: data['physics'],
    tag_pinball: data['pinball'],
    tag_pirates: data['pirates'],
    tag_pixel_graphics: data['pixel_graphics'],
    tag_platformer: data['platformer'],
    tag_point_and_click: data['point_and_click'],
    tag_political: data['political'],
    tag_politics: data['politics'],
    tag_pool: data['pool'],
    tag_post_apocalyptic: data['post_apocalyptic'],
    tag_procedural_generation: data['procedural_generation'],
    tag_programming: data['programming'],
    tag_psychedelic: data['psychedelic'],
    tag_psychological: data['psychological'],
    tag_psychological_horror: data['psychological_horror'],
    tag_puzzle: data['puzzle'],
    tag_puzzle_platformer: data['puzzle_platformer'],
    tag_pve: data['pve'],
    tag_pvp: data['pvp'],
    tag_quick_time_events: data['quick_time_events'],
    tag_rpg: data['rpg'],
    tag_rpgmaker: data['rpgmaker'],
    tag_rts: data['rts'],
    tag_racing: data['racing'],
    tag_real_time_tactics: data['real_time_tactics'],
    tag_real_time: data['real_time'],
    tag_real_time_with_pause: data['real_time_with_pause'],
    tag_realistic: data['realistic'],
    tag_relaxing: data['relaxing'],
    tag_remake: data['remake'],
    tag_replay_value: data['replay_value'],
    tag_resource_management: data['resource_management'],
    tag_retro: data['retro'],
    tag_rhythm: data['rhythm'],
    tag_robots: data['robots'],
    tag_rogue_like: data['rogue_like'],
    tag_rogue_lite: data['rogue_lite'],
    tag_romance: data['romance'],
    tag_rome: data['rome'],
    tag_runner: data['runner'],
    tag_sailing: data['sailing'],
    tag_sandbox: data['sandbox'],
    tag_satire: data['satire'],
    tag_sci_fi: data['sci_fi'],
    tag_science: data['science'],
    tag_score_attack: data['score_attack'],
    tag_sequel: data['sequel'],
    tag_sexual_content: data['sexual_content'],
    tag_shoot_em_up: data['shoot_em_up'],
    tag_shooter: data['shooter'],
    tag_short: data['short'],
    tag_side_scroller: data['side_scroller'],
    tag_silent_protagonist: data['silent_protagonist'],
    tag_simulation: data['simulation'],
    tag_singleplayer: data['singleplayer'],
    tag_skateboarding: data['skateboarding'],
    tag_skating: data['skating'],
    tag_skiing: data['skiing'],
    tag_sniper: data['sniper'],
    tag_snow: data['snow'],
    tag_snowboarding: data['snowboarding'],
    tag_soccer: data['soccer'],
    tag_software: data['software'],
    tag_software_training: data['software_training'],
    tag_sokoban: data['sokoban'],
    tag_souls_like: data['souls_like'],
    tag_soundtrack: data['soundtrack'],
    tag_space: data['space'],
    tag_space_sim: data['space_sim'],
    tag_spectacle_fighter: data['spectacle_fighter'],
    tag_spelling: data['spelling'],
    tag_split_screen: data['split_screen'],
    tag_sports: data['sports'],
    tag_star_wars: data['star_wars'],
    tag_stealth: data['stealth'],
    tag_steam_machine: data['steam_machine'],
    tag_steampunk: data['steampunk'],
    tag_story_rich: data['story_rich'],
    tag_strategy: data['strategy'],
    tag_strategy_rpg: data['strategy_rpg'],
    tag_stylized: data['stylized'],
    tag_submarine: data['submarine'],
    tag_superhero: data['superhero'],
    tag_supernatural: data['supernatural'],
    tag_surreal: data['surreal'],
    tag_survival: data['survival'],
    tag_survival_horror: data['survival_horror'],
    tag_swordplay: data['swordplay'],
    tag_tactical: data['tactical'],
    tag_tactical_rpg: data['tactical_rpg'],
    tag_tanks: data['tanks'],
    tag_team_based: data['team_based'],
    tag_tennis: data['tennis'],
    tag_text_based: data['text_based'],
    tag_third_person: data['third_person'],
    tag_third_person_shooter: data['third_person_shooter'],
    tag_thriller: data['thriller'],
    tag_time_attack: data['time_attack'],
    tag_time_management: data['time_management'],
    tag_time_manipulation: data['time_manipulation'],
    tag_time_travel: data['time_travel'],
    tag_top_down: data['top_down'],
    tag_top_down_shooter: data['top_down_shooter'],
    tag_touch_friendly: data['touch_friendly'],
    tag_tower_defense: data['tower_defense'],
    tag_trackir: data['trackir'],
    tag_trading: data['trading'],
    tag_trading_card_game: data['trading_card_game'],
    tag_trains: data['trains'],
    tag_transhumanism: data['transhumanism'],
    tag_turn_based: data['turn_based'],
    tag_turn_based_combat: data['turn_based_combat'],
    tag_turn_based_strategy: data['turn_based_strategy'],
    tag_turn_based_tactics: data['turn_based_tactics'],
    tag_tutorial: data['tutorial'],
    tag_twin_stick_shooter: data['twin_stick_shooter'],
    tag_typing: data['typing'],
    tag_underground: data['underground'],
    tag_underwater: data['underwater'],
    tag_unforgiving: data['unforgiving'],
    tag_utilities: data['utilities'],
    tag_vr: data['vr'],
    tag_vr_only: data['vr_only'],
    tag_vampire: data['vampire'],
    tag_video_production: data['video_production'],
    tag_villain_protagonist: data['villain_protagonist'],
    tag_violent: data['violent'],
    tag_visual_novel: data['visual_novel'],
    tag_voice_control: data['voice_control'],
    tag_voxel: data['voxel'],
    tag_walking_simulator: data['walking_simulator'],
    tag_war: data['war'],
    tag_wargame: data['wargame'],
    tag_warhammer_40k: data['warhammer_40k'],
    tag_web_publishing: data['web_publishing'],
    tag_werewolves: data['werewolves'],
    tag_western: data['western'],
    tag_word_game: data['word_game'],
    tag_world_war_i: data['world_war_i'],
    tag_world_war_ii: data['world_war_ii'],
    tag_wrestling: data['wrestling'],
    tag_zombies: data['zombies'],
    tag_e_sports: data['e_sports'],
});

module.exports = { objectImport, dbIndexScheme };